server:
  port: 8080
spring:
  application:
    name: microservices-app
  jpa:
    show-sql: false 
    hibernate:
      ddl-auto: update
    properties: 
      dialect: org.hibernate.dialect.MySQL8Dialect
  jmx:
    enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/codevelopment?allowPublicKeyRetrieval=true&sslMode=DISABLED
    username: root
    password: codevelopment
