server:
  port: 8082
  
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url: 
      defaultZone: http://localhost:8081/eureka/
    register-with-eureka: true  
spring:
  application:
    name: core
  jpa:
    show-sql: false 
    hibernate:
      ddl-auto: update
    properties: 
      dialect: org.hibernate.dialect.MySQL8Dialect
  jmx:
    enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/codevelopment?allowPublicKeyRetrieval=true&sslMode=DISABLED
    username: root
    password: codevelopment
#jwt:
#  config:
#    type: signed    
